# Generated by Django 5.2.4 on 2025-07-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='category',
            field=models.CharField(choices=[('certificate', '자격증'), ('award', '수상')], default='certificate', max_length=20, verbose_name='분류'),
        ),
    ]
